# Generated by Django 4.1.7 on 2023-06-14 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=10)),
                ('calle', models.CharField(max_length=10)),
                ('numero', models.IntegerField()),
                ('abierta', models.BooleanField()),
                ('fecha_apertura', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('numeroOficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenApp.oficina')),
            ],
        ),
    ]
